### PR TITLE
add color settings for term and ansi-term

### PR DESCRIPTION
**Pull request by ouonline**
color settings for `M-x term` and `M-x ansi-term`. I am not sure whether the `term-bold` is necessary.

### CODE REVIEW

**Comment by fniessen** [comment]
Dear @ouonline , is it correct that the value of the background is the same as the value of the foreground?  In other words, anything written using that face would be totally invisible, right?

**Comment by ouonline** [comment]
> Dear @ouonline , is it correct that the value of the background is the same as the value of the foreground? In other words, anything written using that face would be totally invisible, right?

I tried those color settings in my emacs 27.1 GUI and the backound didn't take effect indeed...I forced push a new commit that removed the `background` options and added other default color settings to make these would work exactly as what I want.

**Comment by ouonline** [comment]
insert in alphabetical order

**Comment by ouonline** [comment]
I put these settings in my own .emacs.

**Pull request closed without merging**
