### PR TITLE
Add black version of theme

### PR DESCRIPTION
**Pull request by thblt**
Adds:

 - A dark version of the theme, automatically generated by converting colors.
 - The script and data used.

As discussed in #21.

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Could you please add a screenshot? :)

**Comment by thblt** [comment]
You can find a screenshot of a preliminary version of leuven-dark in [my initial comment in issue #32](https://github.com/fniessen/emacs-leuven-theme/issues/21#issuecomment-257036048).  I'm not sure it's really necessary to add one to the PR:  Leuven-dark is really nothing more than an automatically generated base someone else could build on.  Maybe some lines in the README to announce its existence could be enough.   What does @fniessen thinks?

**Comment by fniessen** [comment]
I'm overloaded ATM. Though, thought I really needed to accept your kind PR ASAP... At some point, hopefully soon, I will add newer screenshots, and announce it properly. Thanks!

**Comment by hyiltiz** [comment]
Is it available in melpa? I installed leuven via `list-packages` but its dark version has never showed up.

**Pull request merged**
